refactor: Redesign package architecture for native DPkg payload installation, dropping custom font installation scripts and checksums.

diff --git a/debian/preinst b/debian/preinst
--- a/debian/preinst
+++ b/debian/preinst
@@ -3,13 +3,10 @@ set -e
 
 . /usr/share/debconf/confmodule
 
-db_input high msttcorefonts/accepted-mscorefonts-eula || true
-db_go || true
-
 db_get msttcorefonts/accepted-mscorefonts-eula
 if [ "$RET" != "true" ]; then
-	echo "EULA not accepted" >&2
-	exit 1
+    echo "EULA not accepted, aborting installation." >&2
+    exit 1
 fi
 
 #DEBHELPER#
